#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 19 10:30:39 2019

@author: lauraannf
"""

from pymongo import MongoClient
from pprint import pprint
client = MongoClient()
db = client.admin
serverStatusResult = db.command("serverStatus")
pprint(serverStatusResult)